[package]
name = "announcements"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
chrono = { version = "0.4.40", features = ["serde"] }
lazy_static = "1.5.0"
log = "0.4.26"
md5 = "0.7.0"
quick-xml = { version = "0.37.2", features = ["serde", "serialize"] }
redis = { version = "0.29.1", features = ["tls-rustls"] }
regex = "1.11.1"
reqwest = { version = "0.12.14", features = ["charset", "http2", "json", "macos-system-configuration", "rustls-tls"], default-features = false }
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
serde_json = "1.0.140"
structured-logger = "1.0.3"
tokio = { version = "1.44.1", features = ["full"] }
